name: third
description: A new Flutter application.

version: 1.0.0+1

environment:
 sdk: ">=2.0.0-dev.68.0 <3.0.0"




dependencies:
  flutter:
    sdk: flutter
  # Add the following line
  firebase_core: ^0.2.5
  google_maps_flutter: ^0.5.11
  http: ^0.12.0
  firebase_messaging: ^4.0.0+1
  #FIRESTORE
          # This dependency was added during initial configuration.

 # add this line
firebase_auth: 0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
   uses-material-design: true
   assets:
    - assets/logo.png